config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  get 'about', to: 'pages#about'
  get 'projects', to: 'pages#projects'
  get 'blog', to: 'pages#blog'
  get 'contact', to: 'pages#contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Localization
end

app/controllers/concerns/localization.rb
module Localization
  extend ActiveSupport::Concern

  included do
    before_action :set_locale

    protected

    def set_locale
      I18n.locale = params[:locale] || I18n.default_locale
    end

    private

    def default_url_options
      { locale: I18n.locale == I18n.default_locale ? nil : I18n.locale }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end

  def projects
  end

  def blog
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='<%= I18n.locale %>'>
  <head>
    <title>SpaceTravel</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>
  <body>
    <div id="page">
      <%= render 'shared/header' %>
      <%= yield %>
      <%= render 'shared/footer' %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<div id="body" class="about">
  <div class="header">
    <div>
      <h1>About</h1>
      <h2>We Have Free Templates for Everyone</h2>
      <p>Our website templates are created with inspiration, checked for quality and originality and meticulously sliced and coded. What’s more, they’re absolutely free! You can do a lot with them. You can modify them. You can use them to design websites for clients, so long as you agree with the <a href="https://freewebsitetemplates.com/about/terms/">Terms of Use</a>. You can even remove all our links if you want to.</p>
    </div>
  </div>
  <div class="body">
    <div>
      <img src="images/earth-satellite.jpg" alt="">
      <h2>We Have More Templates for You</h2>
      <p>Looking for more templates? Just browse through all our <a href="https://freewebsitetemplates.com/">Free Website Templates</a> and find what you’re looking for. But if you don’t find any website template you can use, you can try our <a href="https://freewebsitetemplates.com/freewebdesign/">Free Web Design</a> service and tell us all about it. Maybe you’re looking for something different, something special. And we love the challenge of doing something different and something special.</p>
    </div>
  </div>
  <div class="footer">
    <div>
      <img src="images/space-shuttle.png" alt="">
      <h2>Be Part of Our Community</h2>
      <p>If you’re experiencing issues and concerns about this website template, join the discussion <a href="https://freewebsitetemplates.com/forums/">on our forum</a> and meet other people in the community who share the same interests with you.</p>
    </div>
  </div>
  <div class="section">
    <div>
      <h2>Template Details</h2>
      <p>Design Version 1. Code version 3. Website Template details, discussion and updates for this <a href="https://freewebsitetemplates.com/discuss/spacescience/"> Space Science Website Template</a>. Website Template design by <a href="https://freewebsitetemplates.com/">Free Website Templates</a>. Please feel free to remove some or all the text and links of this page and replace it with your own About content.</p>
    </div>
  </div>
</div>

app/views/pages/blog.html.erb
<div id="body">
  <div class="header">
    <div>
      <h1>Blog</h1>
      <div class="article">
        <ul>
          <li>
            <a href="singlepost.html"><img src="<%= asset_path('astronaut.jpg') %>" alt=""></a>
            <h1>SUCCESFUL REPAIR OF THE MX-1 SAT</h1>
            <span>FEBRUARY 6, 2023</span>
            <p>This website template has been designed by Free Website Templates for you, for free. You can replace all this text with your own text.</p>
            <a href="singlepost.html" class="more">Read More</a>
          </li>
          <li>
            <a href="singlepost.html"><img src="<%= asset_path('satellite-dish.jpg') %>" alt=""></a>
            <h1>ALIEN SIGNAL DISCOVERY</h1>
            <span>FEBRUARY 3, 2023</span>
            <p>You can remove any link to our website from this website template, you're free to use this website template without linking back to us.</p>
            <a href="singlepost.html" class="more">Read More</a>
          </li>
        </ul>
      </div>
      <div class="sidebar">
        <ul>
          <li>
            <h1>FEATURED POSTS</h1>
            <a href="singlepost.html"><img src="<%= asset_path('moon-satellite.jpg') %>" alt=""></a>
            <h2>SOYUZ TMA-M</h2>
            <span>FEBRUARY 6, 2023</span>
          </li>
          <li>
            <h1>RECENT POSTS</h1>
            <ul>
              <li>
                <a href="singlepost.html"><img src="<%= asset_path('alien-life.jpg') %>" alt=""></a>
                <h2>ALIEN LIFE</h2>
                <span>FEBRUARY 3, 2023</span>
              </li>
              <li>
                <a href="singlepost.html"><img src="<%= asset_path('galaxy.jpg') %>" alt=""></a>
                <h2>THE GALAXY</h2>
                <span>FEBRUARY 1, 2023</span>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/pages/contact.html.erb
<div id="body">
  <div class="header">
    <div class="contact">
      <h1>Contact</h1>
      <h2>DO NOT HESITATE TO CONTACT US</h2>
      <form action="index.html">
        <input type="text" name="Name" value="Name" onblur="this.value=!this.value?'Name':this.value;" onfocus="this.select()" onclick="this.value='';">
        <input type="text" name="Email Address" value="Email Address" onblur="this.value=!this.value?'Email Address':this.value;" onfocus="this.select()" onclick="this.value='';">
        <input type="text" name="Subject" value="Subject" onblur="this.value=!this.value?'Subject':this.value;" onfocus="this.select()" onclick="this.value='';">
        <textarea name="message" cols="50" rows="7">Message</textarea>
        <input type="submit" value="Send" id="submit">
      </form>
    </div>
  </div>
</div>

app/views/pages/index.html.erb
<div id="body" class="home">
  <div class="header">
    <div>
      <img src="<%= asset_path('satellite.png') %>" alt="" class="satellite">
      <h1>SOYUZ TMA-M</h1>
      <h2>SPACECRAFT</h2>
      <a href="blog.html" class="more">Read More</a>
      <h3>FEATURED PROJECTS</h3>
      <ul>
        <li>
          <a href="projects.html"><img src="<%= asset_path('project-image1.jpg') %>" alt=""></a>
        </li>
        <li>
          <a href="projects.html"><img src="<%= asset_path('project-image2.jpg') %>" alt=""></a>
        </li>
        <li>
          <a href="projects.html"><img src="<%= asset_path('project-image3.jpg') %>" alt=""></a>
        </li>
        <li>
          <a href="projects.html"><img src="<%= asset_path('project-image4.jpg') %>" alt=""></a>
        </li>
      </ul>
    </div>
  </div>
  <div class="body">
    <div>
      <h1>OUR MISSION</h1>
      <p>This website template has been designed by Free Website Templates for you, for free. You can replace all this text with your own text.</p>
    </div>
  </div>
  <div class="footer">
    <div>
      <ul>
        <li>
          <h1>FEATURED VIDEO</h1>
          <a href="blog.html"><img src="<%= asset_path('mars-rover.jpg') %>" alt=""><span></span></a>
        </li>
        <li>
          <h1>LATEST BLOG</h1>
          <ul>
            <li>
              <a href="blog.html"><img src="<%= asset_path('finding-planet.jpg') %>" alt=""></a>
              <h1>FINDING PLANET X-123</h1>
              <span>FEBRUARY 6, 2023</span>
              <a href="blog.html" class="more">Read More</a>
            </li>
            <li>
              <a href="blog.html"><img src="<%= asset_path('new-satellitedish.jpg') %>" alt=""></a>
              <h1>NEW SATELLITE DISH</h1>
              <span>FEBRUARY 3, 2023</span>
              <a href="blog.html" class="more">Read More</a>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/pages/projects.html.erb
<div id="body">
  <div class="header">
    <div>
      <h1>Projects</h1>
      <ul>
        <li>
          <a href="proj1.html"><img src="<%= asset_path('curious-rover.jpg') %>" alt=""></a>
          <div>
            <h1>MARS CURIOSITY ROVER </h1>
            <p>Our website templates are created with inspiration, checked for quality and originality and meticulously sliced and coded. What’s more, they’re absolutely free! You can do a lot with them. You can modify them. You can use them to design websites for clients, so long as you agree with the Terms of Use.</p>
            <a href="proj1.html" class="more">Read More</a>
          </div>
        </li>
        <li>
          <a href="proj1.html"><img src="<%= asset_path('space-station.jpg') %>" alt=""></a>
          <div>
            <h1>INTERTERNATIONAL SPACE STATION</h1>
            <p>Looking for more templates? Just browse through all our Free Website Templates and find what you’re looking for. But if you don’t find any website template you can use, you can try our Free Web Design service and tell us all about it. Maybe you’re looking for something different, something special.</p>
            <a href="proj1.html" class="more">Read More</a>
          </div>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div id="footer">
  <div class="connect">
    <div>
      <h1>FOLLOW OUR  MISSIONS ON</h1>
      <div>
        <a href="http://freewebsitetemplates.com/go/facebook/" class="facebook">facebook</a>
        <a href="http://freewebsitetemplates.com/go/twitter/" class="twitter">twitter</a>
        <a href="http://freewebsitetemplates.com/go/googleplus/" class="googleplus">googleplus</a>
        <a href="http://pinterest.com/fwtemplates/" class="pinterest">pinterest</a>
      </div>
    </div>
  </div>
  <div class="footnote">
    <div>
      <p>&copy; 2023 BY SPACE PROSPECTION | ALL RIGHTS RESERVED</p>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<div id="header">
  <div>
    <a href="<%= root_path %>" class="logo"><img src="<%= asset_path('logo.png') %>" alt=""></a>
    <ul id="navigation">
      <li class="selected">
        <a href="<%= root_path %>">Home</a>
      </li>
      <li>
        <a href="<%= about_path %>">About</a>
      </li>
      <li class="menu">
        <a href="<%= projects_path %>">Projects</a>
        <ul class="primary">
          <li>
            <a href="proj1.html">proj 1</a>
          </li>
        </ul>
      </li>
      <li class="menu">
        <a href="<%= blog_path %>">Blog</a>
        <ul class="secondary">
          <li>
            <a href="singlepost.html">Single post</a>
          </li>
        </ul>
      </li>
      <li>
        <a href="<%= contact_path %>">Contact</a>
      </li>
    </ul>
  </div>
</div>